language: node_js
node_js:
  - "10"
install:
  - npm install
stages:
  - test
  - running
  - name: delivery
    if: branch = master
jobs:
  include:
    - stage: test
      script: npm test 
    - stage: running
      script: npm start
    - stage: delivery
      script: npm test