language: node_js
node_js:
  - "10"
install:
  - npm install
jobs:
  include:
    - stage: test
      script: npm test 
    - stage: running
      script: npm start
    - stage: delivery
      if: branch = master
      script: npm test