language: node_js
node_js:
  - "10"
install:
  - npm install
stages:
  - name: "Quality Gates" 
    if: type = pull_request
        AND branch != master
  - name: "Build"
    if: type = pull_request
        AND branch != master
  - name: "Delivery"
    if: type != pull_request
        AND branch = master
jobs:
  include:
    - stage: "Quality Gates"
      name: "Linter"
      script: npm test 
    - script: npm test 
      name: "Unit Tests"
    - stage: delivery
      script: echo 'DELIVERYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY'