language: node_js
node_js:
- '10'
install:
- npm install
stages:
- name: Delivery
  if: type != pull_request AND branch = master
jobs:
  include:
  - stage: Delivery
    script: npm run deploy
branches:
  only:
  - master
addons:
  ssh_known_hosts:
  - 68.183.2.140
  
