language: node_js
node_js:
  - "10"
install:
  - npm install
jobs:
  include:
    - stage: test
      script: npm test 
    - stage: running
      script: npm start
    - stage: delivery
      script:
        - $TRAVIS_BRANCH == "master" && npm test || exit 0