language: node_js
node_js:
  - "10"
install:
  - npm install
jobs:
  include:
    - stage: test
      script: npm test 
    - stage: running
      script: npm start
    - stage: GitHub Release
      script: echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        on:
          tags: true