language: node_js
node_js:
- '10'
install:
- npm install
stages:
- Test
- name: Delivery
  if: type != pull_request AND branch = master
jobs:
  include:
  - stage: Test
    script: npm test
  - stage: Delivery
    script: npm deploy
branches:
  only:
  - master
